export const text = {
  locale: "ru-RU",
  timeZone: "Europe/Moscow",
  brand: "GigRadar",
  pageTitle: "GigRadar — афиша концертов",
  tagline: "Твоя музыка. Твои концерты.",
  heading: "Музыка рядом",
  // Values must match the cities accepted by the API; labels are display text.
  cities: [
    { value: "Москва", label: "Москва" },
    { value: "Санкт-Петербург", label: "Санкт-Петербург" },
  ],
  sections: {
    concerts: "Афиша",
    artists: "Артисты",
    subscriptions: "Подписки",
    favorites: "Избранное",
    settings: "Настройки",
  },
  icons: {
    brand: "✺",
    concerts: "⌁",
    artists: "♫",
    subscriptions: "◎",
    favorites: "☆",
    settings: "⚙",
    close: "×",
    arrow: "→",
    external: "↗",
  },
  labels: {
    sections: "Разделы",
    city: "Город",
    dateFrom: "Дата с",
    search: "Поиск",
    artistSearch: "Поиск артиста",
    myCity: "Мой город",
    notifications: "Уведомления о концертах",
    performer: "Исполнитель",
    performers: "Исполнители",
    sources: "Источники",
    upcomingConcerts: "Ближайшие концерты",
    also: "Также:",
  },
  placeholders: {
    concertSearch: "Концерт или артист",
    artistSearch: "Имя исполнителя",
    venue: "Площадка уточняется",
  },
  actions: {
    back: "← Назад",
    subscribe: "+ Подписаться",
    subscribed: "Подписаны ✓",
    subscribedDetail: "Вы подписаны",
    unsubscribe: "Отписаться",
    favorite: "☆ В избранное",
    favorited: "В избранном",
    saveFavorite: "Добавить в избранное",
    closeError: "Закрыть",
    webSignIn: "Войти через Telegram",
    webSignOut: "Выйти",
    previous: "← Ранее",
    next: "Далее →",
  },
  notices: {
    postponed: "Организатор изменил время события. Проверьте информацию у источника.",
    cancelled: "Источник подтвердил отмену события.",
  },
  states: {
    concertsLoading: "Загружаем афишу…",
    artistsLoading: "Ищем артистов…",
    noConcerts: "По этим условиям концертов пока нет. Попробуйте другой город или дату.",
    noArtists: "Артистов пока нет.",
    noUpcomingConcerts: "Ближайших концертов пока нет.",
    subscriptionsSignIn: "Войдите через Telegram, чтобы подписываться на артистов.",
    noSubscriptions: "Вы пока не подписаны на артистов. Найдите их в каталоге.",
    favoritesSignIn: "Войдите через Telegram, чтобы сохранять концерты.",
    noFavorites: "Здесь появятся концерты, которые вы сохранили.",
    settingsSignIn: "Настройки доступны после входа через Telegram.",
    webLoginChecking: "Проверяем доступность входа…",
    webLoginUnavailable: "Вход через браузер пока недоступен.",
  },
  errors: {
    favoritesSignIn: "Избранное доступно после входа через Telegram.",
    subscriptionsSignIn: "Подписки доступны после входа через Telegram.",
    webLoginFailed: "Не удалось войти через Telegram. Попробуйте снова.",
    webLoginCancelled: "Вход через Telegram отменён.",
    webLoginUnavailable: "Telegram временно недоступен. Попробуйте позже.",
    http: (status: number) => `Ошибка ${status}`,
  },
  sourceNames: {
    timepad: "Timepad",
    kudago: "KudaGo",
  } as Record<string, string>,
  format: {
    openConcert: (title: string) => `Открыть ${title}`,
    updatedAt: (date: string) => `Обновлено ${date}`,
    pageRange: (first: number, last: number, total: number) => `${first}–${last} из ${total}`,
  },
} as const;
